### ISSUE TITLE
导入系统自带告警规则后选择企业微信告警通知未触发

### ISSUE THREAD

**Issue by laizhimingong** [n9e/n9e.github.io#14]
导入系统自带告警规则，然后配置通过企业微信告警后，无法触发企业微信告警。
自定义告警规则选择企业微信告警，正常触发企业微信告警通知

前端版本：5.2.0
后端版本：5.6.0

**Comment by UlricQin** [comment]
既然有成功的例子了，对照一下策略哪里有不同不就行了.....

**Comment by laizhimingong** [comment]
> 既然有成功的例子了，对照一下策略哪里有不同不就行了.....

嗯，规则编写问题不大，主要是系统自带的导入后未触发企业微信告警通知，这个问题。
不在意手动编写，此问题可以忽略
